/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import koneksi.KoneksiDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.modelKasir;

/**
 *
 * @author basith
 */
public class ViewKasir extends javax.swing.JFrame {
    
    modelKasir model = new modelKasir();
   
   
    public void tampil_combo(){
        try{
            String sql = "Select nama_minuman,harga from input";
            java.sql.Connection conn = (Connection) KoneksiDB.getcon();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
               JnsMnm.addItem(rs.getString("nama_minuman"));
               Integer x = rs.getInt("harga");
               System.out.print(x);
               model.listHarga.put(rs.getString("nama_minuman"),x);
            }
            
            rs.last();
            int jumbalhdata = rs.getRow();
            rs.first();
            
        }catch (Exception e){
            
        }
    }
    
    public ViewKasir()  {
        initComponents();
        tampil_combo();
      
   
        
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jmlDua = new javax.swing.JRadioButton();
        jmlEmpat = new javax.swing.JRadioButton();
        jmlTiga = new javax.swing.JRadioButton();
        jmlLima = new javax.swing.JRadioButton();
        jmlSatu = new javax.swing.JRadioButton();
        JnsMnm = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUang = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BtnBeli = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        BtnBatal1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        TmbMnm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Jenis minuman");

        jLabel3.setText("Jumlah minuman");

        jLabel4.setText("Total harga");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        buttonGroup6.add(jmlDua);
        jmlDua.setText("2x");
        jmlDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlDuaActionPerformed(evt);
            }
        });

        buttonGroup6.add(jmlEmpat);
        jmlEmpat.setText("4x");
        jmlEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlEmpatActionPerformed(evt);
            }
        });

        buttonGroup6.add(jmlTiga);
        jmlTiga.setText("3x");
        jmlTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlTigaActionPerformed(evt);
            }
        });

        buttonGroup6.add(jmlLima);
        jmlLima.setText("5x");
        jmlLima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlLimaActionPerformed(evt);
            }
        });

        buttonGroup6.add(jmlSatu);
        jmlSatu.setSelected(true);
        jmlSatu.setText("1x");
        jmlSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlSatuActionPerformed(evt);
            }
        });

        JnsMnm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--" }));
        JnsMnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JnsMnmActionPerformed(evt);
            }
        });

        jLabel1.setText("Uang Pelanggan");

        jLabel6.setText("Kembalian");

        txtUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangActionPerformed(evt);
            }
        });

        txtkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalianActionPerformed(evt);
            }
        });

        btnKembali.setText("Hasil kembalian");
        btnKembali.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                btnKembaliComponentRemoved(evt);
            }
        });
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JnsMnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jmlSatu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jmlTiga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmlLima))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jmlDua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmlEmpat))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtkembalian, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnKembali)))
                .addGap(119, 119, 119))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JnsMnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jmlSatu)
                            .addComponent(jmlTiga)
                            .addComponent(jmlLima))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jmlEmpat)
                            .addComponent(jmlDua))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("KASIR MINUMAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtnBeli.setBackground(new java.awt.Color(0, 204, 204));
        BtnBeli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBeli.setForeground(new java.awt.Color(255, 255, 255));
        BtnBeli.setText("Beli");
        BtnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBeliActionPerformed(evt);
            }
        });

        BtnBatal.setBackground(new java.awt.Color(0, 204, 204));
        BtnBatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBatal.setForeground(new java.awt.Color(255, 255, 255));
        BtnBatal.setText("Batal");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        BtnBatal1.setBackground(new java.awt.Color(0, 204, 204));
        BtnBatal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBatal1.setForeground(new java.awt.Color(255, 255, 255));
        BtnBatal1.setText("Keluar");
        BtnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatal1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Tambah Minuman");

        TmbMnm.setText("Tambah");
        TmbMnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TmbMnmActionPerformed(evt);
            }
        });
        jMenu1.add(TmbMnm);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(BtnBeli)
                .addGap(33, 33, 33)
                .addComponent(BtnBatal)
                .addGap(29, 29, 29)
                .addComponent(BtnBatal1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBeli)
                    .addComponent(BtnBatal)
                    .addComponent(BtnBatal1))
                .addGap(0, 57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmlSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlSatuActionPerformed
        // TODO add your handling code here:
        kaliTextHarga(1);
    }//GEN-LAST:event_jmlSatuActionPerformed

    private void JnsMnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JnsMnmActionPerformed
        // TODO add your handling code here:
        
        kaliTextHarga(1);
        //bALIKIN KE X1
        jmlSatu.doClick();
    }//GEN-LAST:event_JnsMnmActionPerformed
        void Kembalian(Integer a){
//    a = Integer.getInteger(String.valueOf(txtUang));
//    kembalian = a - ;
}
  
    
    private void jmlEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlEmpatActionPerformed
        // TODO add your handling code here:
        kaliTextHarga(4);
    }//GEN-LAST:event_jmlEmpatActionPerformed
    void kaliTextHarga(Integer i){
 
    }
    private void TmbMnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TmbMnmActionPerformed
        InputMinuman IM = null;
        try {
            IM = new InputMinuman();
        } catch (SQLException ex) {
            Logger.getLogger(ViewKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
        IM.setLocationRelativeTo(this);
        IM.setVisible(true);
       
    }//GEN-LAST:event_TmbMnmActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        jmlSatu.doClick();
        try {
            model.Batal(this);
        } catch (SQLException ex) {
            Logger.getLogger(ViewKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBeliActionPerformed
        try {
            model.Beli(this);
        } catch (SQLException ex) {
            Logger.getLogger(ViewKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnBeliActionPerformed

    private void jmlTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlTigaActionPerformed
        // TODO add your handling code here:
        kaliTextHarga(3);
    }//GEN-LAST:event_jmlTigaActionPerformed

    private void jmlDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlDuaActionPerformed
        // TODO add your handling code here:
        kaliTextHarga(2);
    }//GEN-LAST:event_jmlDuaActionPerformed

    private void jmlLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlLimaActionPerformed
        kaliTextHarga(5);
    }//GEN-LAST:event_jmlLimaActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void BtnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatal1ActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_BtnBatal1ActionPerformed

    private void txtUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        int bil1;
        int bil2;
        int hasil;
        
        bil1= Integer.parseInt(txtHarga.getText());
        bil2= Integer.parseInt(txtUang.getText());
        hasil = bil2-bil1;
        txtkembalian.setText(Integer.toString(hasil));
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianActionPerformed

    private void btnKembaliComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_btnKembaliComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnBatal;
    public javax.swing.JButton BtnBatal1;
    public javax.swing.JButton BtnBeli;
    public javax.swing.JComboBox JnsMnm;
    private javax.swing.JMenuItem TmbMnm;
    public javax.swing.JButton btnKembali;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JRadioButton jmlDua;
    public javax.swing.JRadioButton jmlEmpat;
    public javax.swing.JRadioButton jmlLima;
    public javax.swing.JRadioButton jmlSatu;
    public javax.swing.JRadioButton jmlTiga;
    public javax.swing.JTextField txtHarga;
    public javax.swing.JTextField txtUang;
    public javax.swing.JTextField txtkembalian;
    // End of variables declaration//GEN-END:variables
}
